name: Adcash Anti-Adblock Cron

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write # Garante explicitamente a permissão de escrita

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Executar atualização do Script
      run: node atualizar-adcash.js

    - name: Commit e Push para o GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Cria o arquivo vazio caso ele não exista para o git não dar erro
        touch adcash-zone.js
        git add adcash-zone.js
        
        git diff --quiet && git diff --staged --quiet || (git commit -m "chore: adcash script update [skip ci]" && git push)
